defaults:
  run:
    shell: bash
    working-directory: .
name: Precommit checks
on: [push]
jobs:
  PrecommitChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - 
        name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: Print cwd
        run: pwd
      - name: ls
        run: echo "$(ls)"
      - name: Add poetry to system path
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install python
        run: poetry install --no-dev
      - name: precommit checks
        run: poetry run ./scripts/checks

